//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextRepls.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextRepls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   name〓Text Repls
        ///# MainForm 폼
        ///btnadd〓Add
        ///lbladdorg〓Org
        ///lbladdnew〓Chg
        ///btnreplsave〓Save\r\nList
        ///btnreplread〓Open\r\nList
        ///lstreplsclmorg〓From
        ///lstreplsclmnew〓To
        ///tabtextconv〓Text conv
        ///tabbatchconv〓Batch conv
        ///btngoreplace〓Conv
        ///lblbatchfilelist〓File list
        ///lstconvfilesclmfilename〓File name
        ///lstconvfilesclmpath〓Directory
        ///btnbatchsave〓Save\r\nList
        ///btnbatchopen〓Open\r\nList
        ///btnbatchrun〓Conv
        ///# MainForm 코드
        ///warningclose〓Changes found, continue to close?
        ///needconfirm〓Confirm
        ///warningreplread〓Changes found,[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   name〓텍스트 내용 여러개 바꾸기
        ///# MainForm 폼
        ///btnadd〓더하기
        ///lbladdorg〓원래
        ///lbladdnew〓바꿈
        ///btnreplsave〓바꿀꺼\r\n쓰기
        ///btnreplread〓바꿀꺼\r\n읽기
        ///lstreplsclmorg〓찾을 내용
        ///lstreplsclmnew〓바꿀 내용
        ///tabtextconv〓문장 변환
        ///tabbatchconv〓파일 일괄 변환
        ///btngoreplace〓바꾸기
        ///lblbatchfilelist〓파일 목록
        ///lstconvfilesclmfilename〓파일 이름
        ///lstconvfilesclmpath〓경로
        ///btnbatchsave〓목록\r\n쓰기
        ///btnbatchopen〓목록\r\n읽기
        ///btnbatchrun〓바꾸기
        ///# MainForm 코드
        ///warningclose〓변경된 내용이 있습니다, 닫으시겠습니까?
        ///needconfirm〓확인해주세요
        ///warningreplread〓변경된 내용이 있습니다, 계속 읽으시겠습니까?
        ///dlgopentitle〓바꿀 문자열이 들어 있는 파일 [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_ko {
            get {
                return ResourceManager.GetString("lang_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap noear_202002 {
            get {
                object obj = ResourceManager.GetObject("noear_202002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
